### PR TITLE
Order Ancestors and Descendants By Depth By Default

### PR DESCRIPTION
**Pull request by millllllz**
This may be a personal preference, but I think this aligns more closely to similar projects.

### CODE REVIEW

**Comment by coryodaniel** [comment]
You should be able to [pipe the operations](https://github.com/coryodaniel/arbor/blob/master/test/arbor/descendants_test.exs#L12) into other statements:

```elixir
    test "given a struct w/ returns its descendants" do
      [root | tail] = create_chatter("pupperinos")
      _cat_comments = create_chatter("kittehs")

      dog_thread =
        root
        |> Comment.descendants()
        |> Comment.by_inserted_at()
        |> Repo.all()

      assert dog_thread == tail
    end
```

**Comment by millllllz** [comment]
This may be an odd use case, but having an earlier `inserted_at`, doesn't necessarily indicate that the node is a parent. A new parent could be created and have the child added to it, for example.

**Comment by coryodaniel** [comment]
You should be able to pipe into any Ecto query (order, where, join, etc)

Thanks,

Cory O’Daniel

**Comment by coryodaniel** [comment]
@JasonMiller circling back to this. Do you know if a default order by is set, will ecto overwrite that if someone pipes in an alternate order by or will it merge them?

**Comment by millllllz** [comment]
Doesn't look like this is being maintained anymore.

**Pull request closed without merging**
